baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
pygmentsCodeFences = true
pygmentsUseClasses = true
lastmod = true
theme = "github-style"
[[params.links]]
    title = "Link"
    href = "https://github.com/meik2333"
  [[params.links]]
    title = "Link2"
    href = "https://github.com/mrtuxa"
    icon = "https://avatars.githubusercontent.com/u/69870860"


[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
enableGitalk = false
