baseURL = "https://mrtuxa.link"
languageCode = "en-us"
title = "mrtuxa's blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "mrtuxa"
  description = "Junior Developer"
  github = "mrtuxa"
  email = "mrtuxa@leipzig.freifunk.net"
  url = "https://mrtuxa.link"
  keywords = "blog, freifunk"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "https://avatars.githubusercontent.com/u/69870860"
  location = "Leipzig"
  enableGitalk = true

  [params.gitalk]
    clientID = "dc8d6d147c3c04904fc5" 
    clientSecret = "17cda4f0f3180ed87a4cf65df3be5bc84b048f75" 
    repo = "mywebsite"
    owner = "mrtuxa"
    admin = "mrtuxa"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false

  [[params.links]]
    title = "Link"
    href = "https://freifunk-leipzig.de"
    icon = "https://freifunk-leipzig.de/images/ffl.svg"
  [[params.links]]
    title = "Link2"
    href = "https://dezentrale.space"
    icon = "https://wiki.dezentrale.space/images/2/29/LogoDezentrale-HexaOnly.svg"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
